In [1]:
import pandas as pd

In [4]:
ds_davipola = pd.read_csv('../kit/data/raw/divipola.csv')

In [8]:
ds_davipola.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1122 entries, 0 to 1121
Data columns (total 7 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Código Departamento                              1122 non-null   int64
 1   Nombre Departamento                              1122 non-null   object
 2   Código Municipio                                 1122 non-null   int64
 3   Nombre Municipio                                 1122 non-null   object
 4   Tipo: Municipio / Isla / Área no municipalizada  1122 non-null   object
 5   longitud                                         1122 non-null   object
 6   Latitud                                          1122 non-null   object
dtypes: int64(2), object(5)
memory usage: 61.5+ KB

In [9]:
ds_davipola.describe()

       Código Departamento  Código Municipio
count          1122.000000       1122.000000
mean             38.222816      38656.544563
std              26.538214      26524.369769
min               5.000000       5001.000000
25%              15.000000      15677.250000
50%              25.000000      25840.000000
75%              66.000000      66452.000000
max              99.000000      99773.000000

In [10]:
ds_davipola.isna().sum()

Código Departamento                                0
Nombre Departamento                                0
Código Municipio                                   0
Nombre Municipio                                   0
Tipo: Municipio / Isla / Área no municipalizada    0
longitud                                           0
Latitud                                            0
dtype: int64

In [11]:
ds_davipola.isnull().sum()

Código Departamento                                0
Nombre Departamento                                0
Código Municipio                                   0
Nombre Municipio                                   0
Tipo: Municipio / Isla / Área no municipalizada    0
longitud                                           0
Latitud                                            0
dtype: int64

In [13]:
ds_agrosavia = pd.read_csv('../kit/data/raw/agrosavia.csv', dtype=str)

In [14]:
ds_agrosavia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92738 entries, 0 to 92737
Data columns (total 32 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Secuencial                          92738 non-null  object
 1   Fecha de Análisis                   92738 non-null  object
 2   Departamento                        92738 non-null  object
 3   Municipio                           92736 non-null  object
 4   Cultivo                             92738 non-null  object
 5   Estado                              92738 non-null  object
 6   Tiempo de establecimiento           92738 non-null  object
 7   Topografia                          92738 non-null  object
 8   Drenaje                             92738 non-null  object
 9   Riego                               92738 non-null  object
 10  Fertilizantes aplicados             92738 non-null  object
 11  pH agua:suelo                       92738 non-null  object
 12  Materia organica                    92738 non-null  object
 13  Fósforo Bray II                     92738 non-null  object
 14  Azufre Fosfato monocalcico          92738 non-null  object
 15  Acidez Intercambiable               92738 non-null  object
 16  Aluminio intercambiable             92738 non-null  object
 17  Calcio intercambiable               92738 non-null  object
 18  Magnesio intercambiable             92738 non-null  object
 19  Potasio intercambiable              92738 non-null  object
 20  Sodio intercambiable                92738 non-null  object
 21  capacidad de intercambio cationico  92738 non-null  object
 22  Conductividad electrica             92738 non-null  object
 23  Hierro disponible olsen             92738 non-null  object
 24  Cobre disponible                    92738 non-null  object
 25  Manganeso disponible Olsen          92738 non-null  object
 26  Zinc disponible Olsen               92738 non-null  object
 27  Boro disponible                     92738 non-null  object
 28  Hierro disponible doble acido       92737 non-null  object
 29  Cobre disponible doble acido        92738 non-null  object
 30  Manganeso disponible doble acido    92738 non-null  object
 31  Zinc disponible doble  acido        92738 non-null  object
dtypes: object(32)
memory usage: 22.6+ MB

In [15]:
ds_agrosavia.describe()

,Secuencial,Fecha de Análisis,Departamento,Municipio,Cultivo,Estado,Tiempo de establecimiento,Topografia,Drenaje,Riego,...,Conductividad electrica,Hierro disponible olsen,Cobre disponible,Manganeso disponible Olsen,Zinc disponible Olsen,Boro disponible,Hierro disponible doble acido,Cobre disponible doble acido,Manganeso disponible doble acido,Zinc disponible doble acido
count,92738,92738,92738,92736,92738,92738,92738,92738,92738,92738,...,92738,92738,92738,92738,92738,92738,92737,92738,92738,92738
unique,92738,2388,33,990,282,4,9,13,6,17,...,3567,36134,7060,11363,8648,1903,3212,1075,2565,1498
top,92738,5/08/2016,CUNDINAMARCA,VILLAVICENCIO,Cacao,Por establecer,De 0 a 1 año,Plano,Buen drenaje,No Tiene,...,0.21,ND,<1.00,ND,<1.00,0.11,ND,ND,ND,ND
freq,1,685,14016,2165,11104,33138,35644,30656,49807,41159,...,1790,5872,13832,5872,19301,1430,87951,87952,87952,87952

In [16]:
ds_agrosavia.isna().sum()

Secuencial                            0
Fecha de Análisis                     0
Departamento                          0
Municipio                             2
Cultivo                               0
Estado                                0
Tiempo de establecimiento             0
Topografia                            0
Drenaje                               0
Riego                                 0
Fertilizantes aplicados               0
pH agua:suelo                         0
Materia organica                      0
Fósforo Bray II                       0
Azufre Fosfato monocalcico            0
Acidez Intercambiable                 0
Aluminio intercambiable               0
Calcio intercambiable                 0
Magnesio intercambiable               0
Potasio intercambiable                0
Sodio intercambiable                  0
capacidad de intercambio cationico    0
Conductividad electrica               0
Hierro disponible olsen               0
Cobre disponible                      0
Manganeso disponible Olsen            0
Zinc disponible Olsen                 0
Boro disponible                       0
Hierro disponible doble acido         1
Cobre disponible doble acido          0
Manganeso disponible doble acido      0
Zinc disponible doble  acido          0
dtype: int64

In [17]:
ds_agrosavia.isnull().sum()

Secuencial                            0
Fecha de Análisis                     0
Departamento                          0
Municipio                             2
Cultivo                               0
Estado                                0
Tiempo de establecimiento             0
Topografia                            0
Drenaje                               0
Riego                                 0
Fertilizantes aplicados               0
pH agua:suelo                         0
Materia organica                      0
Fósforo Bray II                       0
Azufre Fosfato monocalcico            0
Acidez Intercambiable                 0
Aluminio intercambiable               0
Calcio intercambiable                 0
Magnesio intercambiable               0
Potasio intercambiable                0
Sodio intercambiable                  0
capacidad de intercambio cationico    0
Conductividad electrica               0
Hierro disponible olsen               0
Cobre disponible                      0
Manganeso disponible Olsen            0
Zinc disponible Olsen                 0
Boro disponible                       0
Hierro disponible doble acido         1
Cobre disponible doble acido          0
Manganeso disponible doble acido      0
Zinc disponible doble  acido          0
dtype: int64

In [19]:
primer_campo = ds_agrosavia.columns[0]

In [22]:
p_numerico = pd.to_numeric(ds_agrosavia[primer_campo].str.strip(), errors="coerce")

In [23]:
p_numerico.isna().sum()

np.int64(0)

In [ ]:
# No se encontró error, ahora se hace sin el str

In [26]:
ds_agrosavia_seg = pd.read_csv('../kit/data/raw/agrosavia.csv', usecols=["Secuencial","Fecha de Análisis","Departamento"])

In [27]:
ds_agrosavia_seg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92738 entries, 0 to 92737
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Secuencial         92738 non-null  int64
 1   Fecha de Análisis  92738 non-null  object
 2   Departamento       92738 non-null  object
dtypes: int64(1), object(2)
memory usage: 2.1+ MB

In [28]:
ds_agrosavia.columns

Index(['Secuencial', 'Fecha de Análisis', 'Departamento'], dtype='object')

In [31]:
for column in ds_agrosavia.columns:
    try:
        issue_column = pd.read_csv('../data/raw/agrosavia.csv', usecols=[column])
    except:
        print('issue', column)

issue Secuencial
issue Fecha de Análisis
issue Departamento

In [33]:
ds_agrosavia.head(10)

   Secuencial Fecha de Análisis  Departamento
0           1         7/01/2014        NARIÑO
1           2        21/08/2014         HUILA
2           3        22/08/2014     ANTIOQUIA
3           4        22/08/2014     ANTIOQUIA
4           5        22/08/2014     ANTIOQUIA
5           6        22/08/2014     ANTIOQUIA
6           7        22/08/2014     ANTIOQUIA
7           8        22/08/2014  CUNDINAMARCA
8           9        22/08/2014     ANTIOQUIA
9          10        22/08/2014  CUNDINAMARCA

In [37]:
import sys
from pathlib import Path
import pandas as pd

# Localizar directorio RAW
actual = Path.cwd().resolve()
REPO = next((ruta for ruta in [actual, *actual.parents] if (ruta / "kit/fuentes.json").is_file() and (ruta / "kit/00_datos.py").is_file()), None)

if REPO is None:
    raise FileNotFoundError("Jupyter debe iniciarse dentro de big-data-postgraduate")

RAW = REPO / "kit/data/raw"

opciones = dict(sep=",", encoding="utf-8-sig", dtype=str, keep_default_na=False)

eva_original = pd.read_csv(RAW / "eva.csv", **opciones)
suelo = pd.read_csv(RAW / "agrosavia.csv", **opciones)
divipola = pd.read_csv(RAW / "divipola.csv", **opciones)

print("EVA:", eva_original.shape)       # Debe dar: (166732, 18)
print("AGROSAVIA:", suelo.shape)        # Debe dar: (92738, 32)
print("DIVIPOLA:", divipola.shape)      # Debe dar: (1122, 7)

EVA: (166732, 18)
AGROSAVIA: (92738, 32)
DIVIPOLA: (1122, 7)